# This function, `add_numbers`, takes in two arguments, `num1` and `num2`, which are both integers.
def add_numbers(num1: int, num2: int) -> int:
    # The function uses the `+` operator to add the two input numbers together.
    result = num1 + num
